/*
 * generated by Xtext
 */
package org.xtext.comp7290.agent;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AgentDSLRuntimeModule extends org.xtext.comp7290.agent.AbstractAgentDSLRuntimeModule {

}
