/*
 * generated by Xtext
 */
package org.xtext.comp7290.agent;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AgentDSLStandaloneSetup extends AgentDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new AgentDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

