/*
 * generated by Xtext
 */
package org.xtext.comp7290.agent.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.comp7290.agent.ui.internal.AgentDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AgentDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AgentDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AgentDSLActivator.getInstance().getInjector(AgentDSLActivator.ORG_XTEXT_COMP7290_AGENT_AGENTDSL);
	}
	
}
