/*
 * generated by Xtext
 */
package org.xtext.comp7290.agent.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AgentDSLUiModule extends org.xtext.comp7290.agent.ui.AbstractAgentDSLUiModule {
	public AgentDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
