/*
 * generated by Xtext
 */
package org.xtext.comp7290.agent.ui.contentassist

import org.xtext.comp7290.agent.ui.contentassist.AbstractAgentDSLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class AgentDSLProposalProvider extends AbstractAgentDSLProposalProvider {
}
