/*
 * generated by Xtext
 */
package org.xtext.comp7290.agent.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.comp7290.agent.services.AgentDSLGrammarAccess;

public class AgentDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AgentDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.comp7290.agent.parser.antlr.internal.InternalAgentDSLParser createParser(XtextTokenStream stream) {
		return new org.xtext.comp7290.agent.parser.antlr.internal.InternalAgentDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public AgentDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AgentDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
