/*
 * generated by Xtext
 */
package org.xtext.comp7290.agent.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AgentDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/comp7290/agent/parser/antlr/internal/InternalAgentDSL.tokens");
	}
}
