/*
 * generated by Xtext
 */
package org.xtext.comp7290.agent;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AgentDSLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.comp7290.agent.ui.internal.AgentDSLActivator.getInstance().getInjector("org.xtext.comp7290.agent.AgentDSL");
	}
	
}
